[versions]

kotlin = "1.6.21"
reactive = "1.2.2"
dateTime = "0.3.2"
serialization = "1.3.3"
coroutines = "1.6.4"
krypto = "2.4.12"
minidns = "1.0.3"

[libraries]

kotlin-kotlinGradlePlug = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-kotlinTestCommon = { group = "org.jetbrains.kotlin", name = "kotlin-test-common", version.ref = "kotlin" }
kotlin-kotlinTestJunit = { group = "org.jetbrains.kotlin", name = "kotlin-test-junit", version.ref = "kotlin" }
kotlin-kotlinTestJs = { group = "org.jetbrains.kotlin", name = "kotlin-test-js", version.ref = "kotlin" }
kotlin-kotlinTestAnnotationsCommon = { group = "org.jetbrains.kotlin", name = "kotlin-test-annotations-common", version.ref = "kotlin" }

kotlinx-datetime = { group = "org.jetbrains.kotlinx", name = "kotlinx-datetime", version.ref = "dateTime" }
kotlinx-serialization-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-core", version.ref = "serialization" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "serialization" }
kotlinx-serialization-gradlePlug = { group = "org.jetbrains.kotlin", name = "kotlin-serialization", version.ref = "kotlin" }

kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutines" }
kotlinx-coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "coroutines" }

reactive-reaktive = { group = "com.badoo.reaktive", name = "reaktive", version.ref = "reactive" }
reactive-testing = { group = "com.badoo.reaktive", name = "reaktive-testing", version.ref = "reactive" }
reactive-utils = { group = "com.badoo.reaktive", name = "utils", version.ref = "reactive" }
reactive-coroutinesInterop = { group = "com.badoo.reaktive", name = "coroutines-interop", version.ref = "reactive" }

krypto = { group = "com.soywiz.korlibs.krypto", name = "krypto", version.ref = "krypto" }

minidns = { group = "org.minidns", name = "minidns-hla", version.ref = "minidns" }

#  = { group = "", name = "", version.ref = "" }

