[versions]

# target versions
java-languageVersion = "17"

# plugins versions
dokka = "1.9.20"
jetbrains-kotlin = "1.9.25"
researchgate-release = "3.1.0"
sphinx = "2.10.1"
task-tree = "4.0.0"
git-versioning = "6.4.4"

# dependencies versions
bouncycastle = "1.79"
coroutines = "1.7.3"
dateTime = "0.6.1"
krypto = "4.0.10"
minidns = "1.1.1"
reactive = "1.3.0"
serialization = "1.6.0"
signalProtocol = "2.8.1"

[plugins]
jetbrains-dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
kotlinx-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "jetbrains-kotlin" }
researchgate-release = { id = "net.researchgate.release", version.ref = "researchgate-release" }
sphinx = { id = "kr.motd.sphinx", version.ref = "sphinx" }

task-tree-plugin = { id = "com.dorongold.task-tree", version.ref = "task-tree" }

[libraries]
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "jetbrains-kotlin" }

kotlinx-datetime = { group = "org.jetbrains.kotlinx", name = "kotlinx-datetime", version.ref = "dateTime" }
kotlinx-serialization-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-core", version.ref = "serialization" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "serialization" }

kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutines" }
kotlinx-coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "coroutines" }

reactive-reaktive = { group = "com.badoo.reaktive", name = "reaktive", version.ref = "reactive" }
reactive-testing = { group = "com.badoo.reaktive", name = "reaktive-testing", version.ref = "reactive" }

krypto = { group = "com.soywiz.korlibs.krypto", name = "krypto", version.ref = "krypto" }

minidns = { group = "org.minidns", name = "minidns-hla", version.ref = "minidns" }

bouncycastle = { group = "org.bouncycastle", name = "bctls-jdk18on", version.ref = "bouncycastle" }

signal-protocol-java = { group = "org.whispersystems", name = "signal-protocol-java", version.ref = "signalProtocol" }